GET http://localhost:8080/api/v2/c/ratings/{{chapterId}}
Accept: application/json
token: {{anotherToken}}

###
GET http://localhost:8080/api/v2/c/rating/61b5d4d84d5260d76567f3b4
Accept: application/json
token: {{anotherToken}}

###
DELETE http://localhost:8080/api/v2/c/rating/61b5d4d84d5260d76567f3b4
Accept: application/json
token: {{anotherToken}}

###
POST http://localhost:8080/api/v2/c/rating
Content-Type: application/json
token: {{anotherToken}}

{
  "chapterId": "{{chapterId}}",
  "value": 4
}

###
PUT http://localhost:8080/api/v2/c/rating/61b5d4d84d5260d76567f3b4
Content-Type: application/json
token: {{anotherToken}}

{
  "chapterId": "{{chapterId}}",
  "value": 3
}

###
