PUT http://localhost:8080/api/v2/c/review/61b4b5ff0e4d895a229937db
Content-Type: application/json
token: {{anotherToken}}

{
  "text": "So Review is updated."
}

###
DELETE http://localhost:8080/api/v2/c/review/61b4b5ff0e4d895a229937db
Content-Type: application/json
token: {{anotherToken}}

{
  "text": "So Review is updated."
}

###
GET http://localhost:8080/api/v2/c/reviews/61c9bb6c01533377503e2805
Accept: application/json

###
POST {{host}}/api/v2/c/review
Content-Type: application/json
token: {{scott}}

{
  "contentId": "{{contentId}}",
  "text": "Wow this review system is lit."
}

###
