GET http://localhost:8080/api/v2/u/save
Accept: application/json
token: {{token}}

###
POST http://localhost:8080/api/v2/u/unfollow/619140ea8b19f6044c1fb7d9
Content-Type: application/json
token: {{token}}

{}

###
POST http://localhost:8080/api/v2/u/follow/619140ea8b19f6044c1fb7d9
Content-Type: application/json
token: {{token}}

{}

###
###GET All Users
GET http://localhost:8080/api/v2/u?include=name_email
Accept: application/json

###GET User By ID
GET http://localhost:8080/api/v2/u/info/619140ea8b19f6044c1fb7d9?populate=1
Accept: application/json
token: {{token}}

###GET Authenticated User
GET http://localhost:8080/api/v2/u/info?populate=true
Accept: application/json
token: {{token}}

###UPDATE Authenticated User
PUT http://localhost:8080/api/v2/u/update
Content-Type: application/json
token: {{token}}

{
  "name": "New Name",
  "gender": "Male"
}

###
