GET http://localhost:8080/api/v2/u/save
Accept: application/json
token: {{token}}

###
POST http://localhost:8080/api/v2/u/unfollow/619140ea8b19f6044c1fb7d9
Content-Type: application/json
token: {{token}}

{}

###
POST http://localhost:8080/api/v2/u/follow/61c9b80c01533377503e27fe
Content-Type: application/json
token: {{scott}}

{}

###
###GET All Users
GET http://localhost:8080/api/v2/u
Accept: application/json

###GET User By ID
GET http://localhost:8080/api/v2/u/info/61c887df8e1d5504ad7dbb4f
Accept: application/json
token: {{token}}

###GET Authenticated User
GET http://localhost:8080/api/v2/u/info
Accept: application/json
token: {{token}}

###UPDATE Authenticated User
PUT http://localhost:8080/api/v2/u/update
Content-Type: application/json
token: {{scott}}

{
  "gender": "Male",
  "phone": "+1 xxx xxx xxx",
  "profileImage": "https://candella.herokuapp.com/images/f_scott.jpg",
  "coverImage": "https://candella.herokuapp.com/images/f_scott_cover.jpg",
  "address": "599 Summit Avenue Saint Paul, Minnesota",
  "pen_name": "F. Scott Fitzgerald",
  "birthdate": "24/9/1896",
  "bio": "So we beat on, boats against the current, borne back ceaselessly into the past."
}

###
