GET http://localhost:8080/files
Accept: application/json

###

POST http://localhost:8080/api/v1/u/login
Content-Type: application/json

{
  "email": "cat@gmail.com",
  "password": "123456"
}

###

POST http://localhost:8080/api/v1/u/login
Content-Type: application/json

{
  "email": "papataco@gmail.com",
  "password": "123456"
}

###
POST http://localhost:8080/api/v1/u/create
Content-Type: application/json

{
  "name": "Ex Machina",
  "email": "papataco@gmail.com",
  "password": "123456"
}

###
