GET http://localhost:8080/api/v1/c/d/comic/619fddc483a396ebfa664816?excludes=tags_lang_ratings_chapters_author
Accept: application/json

###

GET http://localhost:8080/api/v1/c/d/comic?excludes=tags_lang_ratings_thoughts_author
Accept: application/json

###

GET http://localhost:8080/api/v1/c/d/comic
Accept: application/json

###

POST http://localhost:8080/api/v1/c
Content-Type: application/json
token: {{machina}}

{
  "title": "Solo Leveling",
  "alternateNames": [],
  "description": "10 years ago, after “the Gate” that connected the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as “Hunters”. However, not all Hunters are powerful. My name is Sung Jin-Woo, an E-rank Hunter. I’m someone who has to risk his life in the lowliest of dungeons, the “World’s Weakest”. Having no skills whatsoever to display, I barely earned the required money by fighting in low-leveled dungeons… at least until I found a hidden dungeon with the hardest difficulty within the D-rank dungeons! In the end, as I was accepting death, I suddenly received a strange power, a quest log that only I could see, a secret to leveling up that only I know about! If I trained in accordance with my quests and hunted monsters, my level would rise. Changing from the weakest Hunter to the strongest S-rank Hunter!",
  "division": "comic",
  "genre": [
    "61957b15997800bdff0f7822",
    "619fdceb6aaab2c5cd69e2a3",
    "619fdcd46aaab2c5cd69e2a1"
  ],
  "lang": "en",
  "chapters": [
    {
      "name": "Chapter 1",
      "contentImages": [
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/001-3.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/002-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/003-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/004-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/005-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/006-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/007-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/008-3-scaled.jpg",
        "http://readsololevelingmanga.com/wp-content/uploads/2020/01/009-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/010-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/011-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/012-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/013-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/014-3-scaled.jpg",
        "https://readsololevelingmanga.com/wp-content/uploads/2020/01/015-3-scaled.jpg"
      ]
    }
  ],
  "tags": [
    "solo leveling",
    "manhwa"
  ]
}

###
