GET http://localhost:8080/dev/api
Accept: application/json

###
POST http://localhost:8080/dev/api/add_doc?id=17101129&password=241smbsk
Content-Type: application/json

{
  "endpoint": "/u/logout",
  "description": "This end point is used to logout the current user.",
  "response": {
    "code": 201,
    "message": "Logged out Successfully"
  },
  "headers": [
    {
      "name": "token",
      "desc": "Pass the token received after login"
    }
  ]
}

###

