GET http://localhost:8080/api/v1/c/d/literature/619624fe78c932aa105028f4
Accept: application/json

###
GET http://localhost:8080/api/v1/c/d/journal/6196a05b05b7e71563ec47f8

###
GET http://localhost:8080/api/v1/c/d/journal?excludes=tags_lang_ratings_thoughts_author
Accept: application/json

###
POST http://localhost:8080/api/v1/c
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTE0MWY3ZTQ5M2Q0NGM0MzQ3OTgwYiIsImlhdCI6MTYzNzE3MzU2NiwiZXhwIjoxNjM3MjU5OTY2fQ.6DdO6ZYAXJoZHlVYoNooOfQrlkCb7QlMwV4JhQVXpBw

{
  "title": "My title #23",
  "desc": "My desc",
  "division": "literature",
  "category": "story",
  "genre": "61957b15997800bdff0f7822",
  "thoughts": [
    {
      "by": "619137689743cdae07816e7f",
      "value": "Can be better."
    },
    {
      "by": "61913734f24ceeb085e48bcf",
      "value": "Nice one."
    }
  ],
  "ratings" : [
    {
      "by": "619137689743cdae07816e7f",
      "value": 3
    },
    {
      "by": "61913734f24ceeb085e48bcf",
      "value": 4
    }
  ]
}

###

POST http://localhost:8080/api/v1/c
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOTE0MWY3ZTQ5M2Q0NGM0MzQ3OTgwYiIsImlhdCI6MTYzNzI2MTMyOSwiZXhwIjoxNjM3MzQ3NzI5fQ.UDZ6qkacUSC9w40nXSBxdStFbjK-eZAb5IUIHn50Yl8

{
  "title": "A brief history of mankind",
  "desc": "Here we will discuss the history of mankind",
  "division": "journal",
  "genre": "61957b38997800bdff0f7824",
  "thoughts": [
    {
      "by": "619137689743cdae07816e7f",
      "value": "Can be better."
    }
  ],
  "ratings" : [
    {
      "by": "619137689743cdae07816e7f",
      "value": 3
    },
    {
      "by": "61913734f24ceeb085e48bcf",
      "value": 4
    }
  ]
}

###
