GET http://localhost:8080/api/v1/c?excludes=tags_lang_ratings_thoughts_author_alternateNames_genre
Accept: application/json

###

GET http://localhost:8080/api/v1/c/i/content/{{ratingTestId}}
Accept: application/json

###
GET http://localhost:8080/api/v1/c/d/literature/619c8e2443521986b0d96a6e
Accept: application/json

###
GET http://localhost:8080/api/v1/c/d/journal/6196a05b05b7e71563ec47f8

###
GET http://localhost:8080/api/v1/c/d/journal?excludes=tags_lang_ratings_thoughts_author
Accept: application/json

###
POST http://localhost:8080/api/v1/c
Content-Type: application/json
token: {{token}}

{
  "title": "A cat's dilemma",
  "description": "A trash written by kawaii neko chan",
  "division": "literature",
  "category": "story",
  "genre": "61957b15997800bdff0f7822"
}

###
PUT http://localhost:8080/api/v1/c/d/{{divisionName}}/619c8e2443521986b0d96a6e
Content-Type: application/json
token: {{token}}

{
  "title": "A kawaii neko's dilemma by second update machina",
  "description": "A simple thing by kawaii neko chan."
}

###
DELETE http://localhost:8080/api/v1/c/d/{{divisionName}}/619c94e6e20782c52033060e
Content-Type: application/json
token: {{token}}

###

POST http://localhost:8080/api/v1/c
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOWE4ODY3NjQ3NTRlMGZjNDRhNjM3NSIsImlhdCI6MTYzNzUyMTc4OSwiZXhwIjoxNjM3NjA4MTg5fQ.u6WNlImkoHlyDdakORAAiYfFP271Ow-8y-uICRlT6VA

{
  "title": "A brief history of mankind",
  "desc": "Here we will discuss the history of mankind",
  "division": "literature",
  "category": "Story",
  "genre": "61957b38997800bdff0f7824",
  "thoughts": [
    {
      "by": "619137689743cdae07816e7f",
      "value": "Can be better."
    }
  ],
  "ratings": [
    {
      "by": "619137689743cdae07816e7f",
      "value": 3
    },
    {
      "by": "61913734f24ceeb085e48bcf",
      "value": 4
    }
  ]
}

###
